In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1. Opening a csv file from an URL
Enter the data url in the code snippet below

In [ ]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

# 2. Seperate Parameter
if you have a 'tab' seprated data, you can set 'sep' parameter to <em>tab</em>

In [ ]:
pd.read_csv("/kaggle/input/movie-toydata/movie_titles_metadata.tsv", sep="\t")

Here, we dont have Column name, when this occurs, we have option to give it mannualy
# 3. Names Paramenter

In [ ]:
pd.read_csv("/kaggle/input/movie-toydata/movie_titles_metadata.tsv",sep='\t',names=['sno','name','release_year','rating','votes','genres'])

# 4. Index column parameter
When we already have index column, we dont need the deafult index column created, so we define only one as index column

In [ ]:
pd.read_csv('/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_train.csv',index_col='enrollee_id')

# 5. Header Paramerter
it makes given row number as column names

In [ ]:
pd.read_csv('/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_train.csv',header=2)

# 6. use_cols parameter

In [ ]:
pd.read_csv('/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_train.csv',usecols=['enrollee_id','gender','education_level'])

# 7. Skiprow / nrows Parameter

In [ ]:
pd.read_csv('/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_train.csv',nrows=100)

# 8. Encoding Parameter
most dataset are in UTF-8 encoding, but those who are not, you need to define Encoding

In [ ]:
pd.read_csv("/kaggle/input/zomato/zomato.csv")

In [ ]:
pd.read_csv("/kaggle/input/zomato/zomato.csv", encoding="latin-1").head()

# 9. Skip Bad Lines Parameter
In some data there are some errors in some rows, for example there are more number of data in a row than number of columns

So in that case you use this, its very useful

In [ ]:
pd.read_csv("/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_train.csv", error_bad_lines=False)

# 10. dtypes Parameter, to change the dtype of a column
here in above dataset, the target variable is in float, lets convert it in int

In [ ]:
pd.read_csv("/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_train.csv",dtype={'target':int}).info()

# 11. Handling Dates

In [ ]:
pd.read_csv("/kaggle/input/ipldata/IPL.csv", parse_dates=['date']).info()

In [ ]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    if name == "Kings XI Punjab":
        return "KXIP"
    if name == "Delhi Daredevils":
        return "DD"
    if name == "Mumbai Indians":
        return "MI"
    if name == "Kolkata Knight Riders":
        return "KKR"
    else:
        return name

# 12. Convertors
to convert long name to short

In [ ]:
pd.read_csv("/kaggle/input/ipldata/IPL.csv",converters={'team1':rename, 'team2':rename, 'winner':rename, 'toss_winner':rename})

# 13. na_values parameter
to define the what is 'na' value

In [ ]:
pd.read_csv("/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_train.csv",na_values=['Male'])

# 14. Loading a huge dataset in chunks

In [ ]:
dfs = pd.read_csv("/kaggle/input/hr-analytics-job-change-of-data-scientists/aug_train.csv",chunksize=5000)

In [ ]:
for chunks in dfs:
    print(chunks.shape)