<div style="width:100%;text-align: center;"> <img align=middle src="https://c.tenor.com/wJnAGDMfrAcAAAAM/technical-guruji-new-phone.gif" alt="Heat beating" style="height:366px;margin-top:3rem;"> </div>

# <h1 style='background:#E0BBE4; border:0; color:white'><center>üì±EDA: Phones-dataset-from-amazon</center></h1>

# **<span style="color:#cd486b;">üì∞About the Dataset</span>**

This dataset is collected from amazon website and data is about the phones that are available amazon website data

# **<span style="color:#cd486b;">üìÅAbout the files</span>**

This dataset has total 369 rows and 8 columns

> 1.phone_name

> 2.Brand

> 3.rating out of five

> 4.discount in percentage

> 5.real price of phone

> 6.Phones discounted price

> 7.rated by people(how many people rated this phones)

In [ ]:
# Imports

import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
#Custom Colors
class clr:
    S = '\033[1m' + '\033[96m'
    E = '\033[0m'
    
my_colors = ["#E0BBE4", "#957DAD", "#D291BC", "#FEC8D8", "#FFDFD3", "#D1D8FD"]

print(clr.S + "Notebook Color Scheme: " + clr.E)
sns.palplot(sns.color_palette(my_colors))

# **<span style="color:#cd486b;">Explore the data</span>**

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
!pip install openpyxl

In [ ]:
import openpyxl

In [ ]:
df = pd.read_excel('/kaggle/input/phonesonamazon/amazon 1.xlsx')

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.columns

In [ ]:
# Drop the column with Nan values
df.drop('Unnamed: 1',axis = 1, inplace = True)

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.head()

In [ ]:
df.info()

**<span style="color:#957DAD;">We need to convert 2 columns - Rated_people and Offered_price_in_rupee from object into numerics (int or float) to use their values</span>**

In [ ]:
df['Rated_people'] = df['Rated_people'].str.replace(',', '')
df['Rated_people'] = df['Rated_people'].astype(int)

In [ ]:
df['Offered_price_in_rupee'] = df['Offered_price_in_rupee'].str.replace(',', '')
df['Offered_price_in_rupee'] = df['Offered_price_in_rupee'].astype(float)

## **<span style="color:#D291BC;">üëÄLet's Visualize</span>**

In [ ]:
df.head()

In [ ]:
sns.pairplot(data = df)

In [ ]:
plt.figure(figsize = (15, 10))
sns.heatmap(df.corr(), annot = True, cmap = 'summer')

# **<span style="color:#E0BBE4;">ü•ΩLet's see what all we can explore in this dataset</span>**

> 1. Which brand has highest rating?

> 2. Which phone has highest rating by people?

> 3. Highest and lowest priced brand

> 4. Highest and lowest discount

## **<span style="color:#957DAD;">1Ô∏è‚É£Which brand has highest rating?</span>**

In [ ]:
Brand_rating = df['ratting_out_of_five'].max()
brand = df.loc[df['ratting_out_of_five'] == Brand_rating, 'Brand'].iloc[0]
phone = df.loc[df['Brand'] == brand, 'phone_name'].iloc[0]

print(brand,phone, ' has highest rating of ', Brand_rating, 'Out of 5')

In [ ]:
Brand_rating_low = df['ratting_out_of_five'].min()
brand_low = df.loc[df['ratting_out_of_five'] == Brand_rating_low, 'Brand'].iloc[0]
phone = df.loc[df['Brand'] == brand_low, 'phone_name'].iloc[0]

print(brand_low,phone, ' has lowest rating of ', Brand_rating_low, 'Out of 5')

In [ ]:
# --------------------Brand VS Rating------------------------

plt.figure(figsize = (40,20))
sns.catplot(x = 'ratting_out_of_five',
            y = 'Brand',
            kind = "bar",
            height = 7,
            aspect = 2,            
            data = df.head(100)).set(title = "Brand VS Rating");
plt.xticks(rotation = 0)
plt.show()

## **<span style="color:#957DAD;">2Ô∏è‚É£Which phone has highest rating by people?</span>**

In [ ]:
Brand_rating = df['ratting_out_of_five'].max()
brand = df.loc[df['ratting_out_of_five'] == Brand_rating, 'Brand'].iloc[0]
phone = df.loc[df['Brand'] == brand, 'phone_name'].iloc[0]

print(phone, ' has highest rating of ', Brand_rating, 'Out of 5')

In [ ]:
# --------------------Phone VS Rating------------------------

plt.figure(figsize = (40,20))
sns.catplot(x = 'ratting_out_of_five',
            y = 'phone_name',
            kind = "bar",
            height = 10,
            aspect = 5,            
            data = df.head(50)).set(title = "Phone VS Rating");
plt.xticks(rotation = 0)
plt.show()

## **<span style="color:#957DAD;">3Ô∏è‚É£Highest and lowest priced brand</span>**

In [ ]:
price = df['Offered_price_in_rupee'].max()
brand_per_price = df.loc[df['Offered_price_in_rupee'] == price, 'Brand'].iloc[0]

print(brand_per_price, ' is the most priced brand with max price of Rs', price)

In [ ]:
price = df['Offered_price_in_rupee'].min()
brand_per_price = df.loc[df['Offered_price_in_rupee'] == price, 'Brand'].iloc[0]

print(brand_per_price, ' is the most priced brand with min price of Rs', price)

In [ ]:
# --------------------Brand VS Price------------------------

plt.figure(figsize = (40,20))
sns.catplot(x = 'Offered_price_in_rupee',
            y = 'Brand',
            kind = "bar",
            height = 7,
            aspect = 2,            
            data = df.head(100)).set(title = "Brand VS Price");
plt.xticks(rotation = 0)
plt.show()

## **<span style="color:#957DAD;">4Ô∏è‚É£Highest and lowest discount</span>**

In [ ]:
# Which brand offers highest and lowest discounts

discount = df['Percent_off'].min()
brand = df.loc[df['Percent_off'] == discount, 'Brand'].iloc[0]

print(brand, ' phones have least discount of ', discount, '%')

In [ ]:
# Which brand offers highest and lowest discounts

discount = df['Percent_off'].max()
brand = df.loc[df['Percent_off'] == discount, 'Brand'].iloc[0]

print(brand, ' phones have max discount of ', discount, '%')

In [ ]:
# --------------------Brands VS Discount------------------------

plt.figure(figsize = (40,20))
sns.catplot(x = 'Percent_off',
            y = 'Brand',
            kind = "bar",
            height = 7,
            aspect = 2,            
            data = df.head(100)).set(title = "Brand VS Discount");
plt.xticks(rotation = 0)
plt.show()

# **<span style="color:#cd486b;">ü§òConclusion</span>**

**<span style="color:#000000;">#This is not the end of üì±EDA: Phones-dataset-from-amazon</span>** 

**<span style="color:#000000;"> Stay Tuned for more analysis in this notebook..</span>** 

**<span style="color:#000000;">Please share your feedback and suggestions and help me improve üòá </span>**