# sheet Ex

***Q-1***

In [ ]:
radius = float(input('Enter radius of the circle: '))
PI = 3.14159
print('Diameter:', 2 * radius)

print('Circumference:', 2 * PI * radius)

print('Area:', PI * radius * radius)

***Q-2***

In [ ]:
name, age, income = input("Enter user's name, age and income: ").split()

print('Name: ' + name)
print('Age: ' + age)
print('Income: ' + income)

***Q-3***

In [ ]:
O_price = float(input("Enter item's original price: "))

discount = 0.25 * O_price

print('Sale price =', O_price - discount)

***Q-4***

In [ ]:
second = int(input('Enter total second: '))
h = second // 3600
second %= 3600
m = second // 60
second %= 60
print(f"Hours: {h}, minutes: {m}, second: {second}")

***Q-5***

In [ ]:
score1, score2, score3 = map(int, input('Enter 3 test score: ').split())
print(f"Average score: {(score1 + score2 + score3) / 3}")

***Q-6***

In [ ]:
def area(length, width):
    return length*width

In [ ]:
len1, wid1 = map(int,input('Enter length and width for first rectangle: ').split())
len2, wid2 = map(int,input('Enter length and width for second rectangle: ').split())

area1 = area(len1, wid1)
area2 = area(len2, wid2)

if area1 > area2:
    print('First rectangle has the greater area.')
elif area1 < area2:
    print('Second rectangle has the greater area.')
else:
    print('Both recangles have the same area.')

***Q-7***

In [ ]:
n = int(input('Enter a number: '))
print (n+n**2+n**3)

***Q-8***

In [ ]:
temp_C = float(input('Enter temperature in Celsius degree: '))

temp_F = (temp_C * 1.8) + 32

print(f"Temperature in Fahrenheit degree: {temp_F}")

***Q-9***

In [ ]:
x, y = map(int, input('Enter two numbers: ').split())

print('Before swap:')
print(f"First number = {x}, Second number = {y}")

x , y = y , x

print('After swap:')
print(f"First number = {x}, Second number = {y}")

# Sheet 1

***Q-2***

In [ ]:
year = int(input('Enter a year: '))

if year % 4 == 0 and year % 100 != 0:
    print('In',year ,'February has 29 days')
elif year % 400 == 0:
    print('In', year, 'February has 29 days')
else:
    print('In', year, 'February has 28 days')

***Q-4***

In [ ]:
salas = [0,0,0,0,0,0,0]

for i in range(0,7):
    salas[i] = int(input(f"Enter salas of day number {i+1}: "))
    
print('Total salas of the week is: ', sum(salas))


print('\n********************************\n')

#another way to solve this problem 

salas2 = list(map(int,input('Enter sales for each day of the week in one line: ').split())) 

print('Total salas of the week is: ', sum(salas2))


print('\n********************************\n')

#another way to solve this problem 

salas3 = list(map(int,input('Enter sales for each day of the week in one line: ').split())) 

total = 0

for i in salas3:
    total += i
    
print('Total salas of the week is: ', total)

***Q-5***

In [ ]:
lst1 = ['Abd El-fatah', 'Emad', 'Abdall', 'Omar', 'Youssef']
lst2 = [80, 95, 100, 90, 100]
lst3 = list(zip(lst1,lst2))
lst3

***Q-7***

In [ ]:
numbers = [74, 19, 105, 20, -2, 67, 77, 124, -45, 38]
valid_numbers = []
for i in numbers:
    if i >= 0 and i <= 100:
        valid_numbers.append(i)
        
print('Total is: ', sum(valid_numbers))
print('Average is: ', sum(valid_numbers) / len(valid_numbers))

***Q-8***

In [ ]:
number = [2, 3, 4, 5, 6, 7]
squares = [x**2 for x in number]
print(squares)

***Q-9***

In [ ]:
def fun(lst1):
    st = set(lst1)
    lst1 = list(st)
    lst1.sort() 
    return lst1

In [ ]:
# test with numbers
nums = [30, 200, 10, 3, 3, 200, 10]
print(fun(nums))

In [ ]:
# test with strings
strings = ['d','x','b','x','a','d']
print(fun(strings))

***Q-10***

In [ ]:
lst = [2, 10 , 15, 'a', 1.5, 22]

position = int(input('Enter the index you want to delete: ')) 
 
lst.pop(position-1)

print(lst)

***Q-11***

In [ ]:
lst4 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

even = [x for x in lst4 if x % 2 == 0]

print('Even list:', even)

***Q-12***

In [ ]:
lst1_2D = [[1, 2, 3], 
           [4, 5, 6], 
           [7, 8, 9]]
lst2_2D = [[10, 20, 30],
           [40, 50, 60],
           [70, 80, 90]]

rows = len(lst1_2D)
columns = len(lst1_2D[0])

lst3_2D = [[0, 0, 0],
           [0, 0, 0],
           [0, 0, 0]]

for i in range(0,rows):
    for j in range(0,columns):
        lst3_2D[i][j] = lst2_2D[i][j] + lst1_2D[i][j]
 
print ('result matrix: ')

for i in range(0,rows):
    for j in range(0,columns):
        print(lst3_2D[i][j], end = ' ')
    print()

# Sheet 2

***Q-2***

In [ ]:
integers = [200, 150, 120, 80, 60, 17, 181, 23, 100]
print(list(x for x in integers if x > 100))

***Q-3***

In [ ]:
ls1 = [1,2,3]
ls2 = [4,5,6]
ls3 = ls1 + ls2
print(ls3)

***Q-6***

In [ ]:
test_averages = {'Ahmed': 98,
              'Ali': 87,
              'Noura': 92,
              'Ramy': 72,
              'Sally': 89,
              'Mai': 82}
print('These names received a degree higher or equal to 90: ')
for key in test_averages:
    if test_averages[key] >= 90:
        print(key)

***Q-7***

In [ ]:
dic = {}
for x in range(1,11):
    dic[x] = x**2

print(dic)

***Q-8***

In [ ]:
k = ['A', 'B', 'C', 'D', 'E', 'F']
v = [10, 11, 12, 13, 14, 15]
dic1 = {}
for i in range(0,6):
    dic1[k[i]] = v[i]
    
print(dic1)

***Q-11***

In [ ]:
int_ls = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

even_ls = [x for x in int_ls if x % 2 == 0]

print(even_ls)

# Sheet 3

***Q-2***

In [ ]:
arr_ascii = {0:'A', 1:'B', 2:'C', 3:'D', 4:'E', 5:'F', 6:'G', 7:'H', 8:'I'
             ,9:'J', 10:'K', 11:'L', 12:'M', 13:'N', 14:'O', 15:'P', 16:'Q',
           17:'R', 18:'S', 19:'T', 20:'U', 21:'V', 22:'W', 23:'X', 24:'Y', 25:'Z'}
def encryption(st, k):
    stt = '' 
    for i in st:
        if (i != ' '):
            p = ord(i)-65
            c = (p + k) % 26
#             print(c)
            stt += arr_ascii[c]
        else:
            stt += i
    return stt

In [ ]:
st = input('Enter a message: ')
k = int(input('Enter shift amount: '))
st = st.upper()
# print(st)
encryption(st,k)

***Q-4***

In [ ]:
numb = [1,2,3,4,5]
numb2 = [x*10 for x in numb]
dicti = {x:y for x,y in zip(numb,numb2)}
print(dicti)

***Q-7***

In [ ]:
lit = list(map(int,input("Enter list of numbers: "). split()))
#sort
lit_sort = lit.copy()
lit_sort.sort()
print (f"Sorted list: {lit_sort}")
#reverse 
lit_reverse = lit.copy()
lit_reverse.reverse()
print (f"Reversed list: {lit_reverse}")
#highest value
print (f"Highest value: {lit_sort[-1]}")

***Q-8***

In [ ]:
empId = [11, 22, 33, 44, 55]
payRate = [0, 0, 0, 0, 0]
hours = [0, 0, 0, 0, 0]
wages = [0, 0, 0, 0, 0]
for i in range(len(empId)):
    hours[i] = int(input(f"Enter number of hours worked by employee number {empId[i]}: "))
    payRate[i] = int(input(f"Enter hourly pay ratefor employee number {empId[i]}: "))
    
for i in range(0,5):
    wages[i] = hours[i]*payRate[i]
    
for i in range(0,5):
    print(f"employee ID: {empId[i]} has gross wages = {wages[i]}")

***Q-9***

In [ ]:
dc = {'Programming': 82, 'Math': 65, 'Algorithms' : 75}
mn = 100
ky = ""
for i in dc:
    if dc[i] < mn:
        ky = i
        mn = dc[i]
        
print ('Key of minimum value in dicitionary: ' + ky)

***Q-10***

In [ ]:
digits = input('Enter a series of single-digit numbers: ')
sm = 0
for i in digits:
    sm += int(i)
print('sum of digits:',sm)