In [ ]:
import pandas as pd
import numpy as np
import datetime
from datetime import date, timedelta
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
idx=pd.IndexSlice
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
plt.style.use('ggplot')

In [ ]:
data = pd.read_csv('Salary_Data_Based_country_and_race.csv').drop('Unnamed: 0', axis=1)

In [ ]:
data.isna().sum()

In [ ]:
data.loc[data.isna().any(axis=1)]

In [ ]:
data.dropna(inplace=True)

In [ ]:
data.reset_index(drop=True, inplace=True)

In [ ]:
data.duplicated().sum()

In [ ]:
data.drop_duplicates(inplace=True)

In [ ]:
data.reset_index(drop=True, inplace=True)

In [ ]:
data.head()

In [ ]:
data.info()

In [ ]:
data.describe()

In [ ]:
#Job Title Categorization

In [ ]:
data.head()

In [ ]:
data['Job Title'].unique()

In [ ]:
data['Salary'] = data['Salary'].astype('int')

In [ ]:
Software_Engineering = [
        'Software Engineer', 'Software Developer', 'Full Stack Engineer', 'Back-end Developer',
        'Front-end Developer', 'Front End Developer', 'Software Manager', 'Software Project Manager',
        'Senior Software Engineer', 'Senior Software Developer', 'Software Engineer Manager', 'Software Architect']

Data_Science = [
        'Data Analyst', 'Data Scientist', 'Senior Data Scientist', 'Junior Data Analyst',
        'Senior Data Analyst', 'Research Scientist', 'Senior Research Scientist']

Management = [
        'Senior Manager', 'Director', 'Sales Manager', 'Marketing Manager', 'Operations Manager',
        'HR Manager', 'Financial Manager', 'Customer Service Manager', 'VP of Operations',
        'Director of Marketing', 'Director of Operations', 'Director of Finance', 'Director of Sales',
        'Director of Sales and Marketing', 'Director of Business Development', 'Director of Human Resources',
        'Director of Human Capital', 'Director of Engineering', 'Director of Data Science',
        'Strategy Consultant', 'Business Development Manager']

Marketing = [
        'Marketing Analyst', 'Marketing Coordinator', 'Digital Marketing Manager', 'Content Marketing Manager',
        'Marketing Specialist', 'Social Media Specialist', 'Marketing Manager', 'Marketing Director',
        'Digital Marketing Specialist', 'Social Media Manager']

Product_Management = [
        'Product Manager', 'Product Designer', 'Product Marketing Manager', 'Senior Product Manager',
        'Senior Product Designer', 'Director of Product Management', 'Product Development Manager']

Human_Resources =  [
        'HR Generalist', 'Junior HR Generalist', 'Senior HR Manager', 'Human Resources Director',
        'Senior HR Generalist', 'Junior HR Coordinator', 'Human Resources Coordinator', 'Director of HR',
        'Senior Human Resources Manager', 'Senior Human Resources Coordinator', 'Senior HR Specialist']

Sales = [
        'Sales Associate', 'Sales Executive', 'Sales Director', 'Sales Representative',
        'Sales Operations Manager', 'Senior Sales Manager', 'Junior Sales Representative',
        'Senior Sales Representative', 'Junior Sales Associate', 'Senior Account Executive']


Finance = [
        'Financial Analyst', 'Financial Manager', 'Financial Advisor', 'Senior Financial Analyst',
        'Junior Accountant', 'Accountant', 'Junior Account Manager', 'Senior Accountant']

IT = [
        'IT Support', 'IT Manager', 'Technical Writer', 'Technical Support Specialist',
        'IT Support Specialist', 'IT Consultant']


Customer_Service = [
        'Customer Service Rep', 'Customer Service Representative', 'Customer Success Rep',
        'Customer Success Manager', 'Junior Customer Support Specialist']

Research_Science = [
        'Senior Scientist', 'Principal Scientist', 'Research Director']

Web_Development = [
        'Web Developer', 'Junior Web Developer', 'Senior Web Developer', 'Junior Web Designer']
    
Logistics = [
        'Operations Analyst', 'Operations Director', 'Operations Coordinator', 'Senior Operations Manager',
        'Supply Chain Manager', 'Supply Chain Analyst']


Design =  [
        'Graphic Designer', 'UX Designer', 'UX Researcher', 'Creative Director', 'Copywriter',
        'Junior Designer', 'Junior UX Designer']

Administrative = [
        'Administrative Assistant', 'Office Manager', 'Receptionist' ]

HR = [
        'Recruiter', 'Technical Recruiter']

Writing = [
        'Technical Writer', 'Copywriter', 'Digital Content Producer']

Event_Coordination: [
        'Event Coordinator']

In [ ]:
def category(data):
    blanks=[]
    for x in data['Job Title']:
        if x in Software_Engineering:
            blanks.append('Software_Engineering')
        elif x in Data_Science:
            blanks.append('Data_Science')
        elif x in Management:
            blanks.append('Management')
        elif x in Marketing:
            blanks.append('Marketing')
        elif x in Product_Management:
            blanks.append('Product_Management')
        elif x in Human_Resources:
            blanks.append('Human_Resources')
        elif x in Sales:
            blanks.append('Sales')
        elif x in Finance:
            blanks.append('Finance')
        elif x in IT:
            blanks.append('IT')
        elif x in Customer_Service:
            blanks.append('Customer_Service')
        elif x in Research_Science:
            blanks.append('Research_Science')
        elif x in Web_Development:
            blanks.append('Web_Development')
        elif x in Design:
            blanks.append('Design')
        elif x in Administrative:
            blanks.append('Administrative')
        elif x in HR:
            blanks.append('HR')
        elif x in Writing:
            blanks.append('Writing')
        else:
            blanks.append('Event_Coordination')
            
    return blanks

In [ ]:
data['Job Category'] = category(data)

In [ ]:
#Race Cleaning

In [ ]:
data.Race.unique()

In [ ]:
def race(data):
    blanks = []
    for x in data['Race']:
        if x == 'Korean' or x == 'Chinese':
            blanks.append('Asian')
        elif x == 'Welsh' or x == 'Australian':
            blanks.append('White')
        elif x == 'African American':
            blanks.append('Black')
        else:
            blanks.append(x)
    return blanks

In [ ]:
data['Ethnicity'] = race(data)

In [ ]:
data.drop('Race', axis=1, inplace=True)

In [ ]:
#Column Distribution

In [ ]:
for x in data.columns:
    if data[x].dtype != 'float64' and data[x].dtype != 'int64' and x != 'Job Title':
        print(data[x].value_counts().sort_values(ascending=False))
        print('')
        print('')

In [ ]:
def max_out(length):
    return [0.01] + [1] * (length - 1)

max_out(len(df))

In [ ]:
for x in data.columns:
    if data[x].dtype != 'float64' and data[x].dtype != 'int64' and x != 'Job Title':
        df = data[x].value_counts().reset_index()
        
        fig, ax = plt.subplots()
        ax.pie(
            x=df[x],
#             startangle=90,
            labels=df['index'],
            autopct="%.0f%%",
#             shadow=True,
#             explode=max_out(d)
            )
        plt.title(f"{x} In Data Distribution", fontsize=12)

In [ ]:
#Histogram for all non-float columns

In [ ]:
for x in data.columns:
    if data[x].dtype == 'float64' or data[x].dtype == 'int64':
        sns.histplot(data[x])
        plt.title(f'{x} Histogram', fontsize=12)
        plt.show()

In [ ]:
data.info()

In [ ]:
#Age analysis

In [ ]:
sns.histplot(data['Age'], kde=True)

In [ ]:
#Avg Age for all different columns
for x in data.columns:
    if data[x].dtype != 'float64' and data[x].dtype != 'int64' and x != 'Age' and x != 'Job Title':
        plt.figure(figsize=(16, 8))
        df = data.groupby(x)['Age'].mean().sort_values(ascending=False).reset_index()
        sns.barplot(y=x, x='Age', data=df)
        plt.axvline(data.Age.mean(), ls='--', color='black', alpha=0.3)
        plt.title(f'Avg Age for Different {x}')
        plt.show()

In [ ]:
#There was a single phD instead of PhD

data['Education Level'] = data['Education Level'].str.replace('phD', 'PhD')

In [ ]:
data['Education Level'].value_counts()

In [ ]:
#Avg Age of Different Gender of Different Column
for x in ['Country', 'Education Level', 'Country', 'Ethnicity']:
    data.groupby(['Gender', x])['Age'].mean().unstack().T.plot(kind='bar', rot=0, figsize=(14, 6))
    plt.title(f'Avg Age of Different Gender of Different {x}', fontsize=12)

In [ ]:
#Changing Bachors's degree to bachelor's 

data['Education Level'] = data['Education Level'].str.replace("Bachelor's Degree", "Bachelor's")

In [ ]:
data.groupby(['Gender', 'Job Category'])['Age'].mean().unstack().T.plot(kind='bar', rot=35, figsize=(16, 6))
plt.title('Avg Age of Different Gender of Different Job Category');

In [ ]:
#Gender analysis

In [ ]:
data.Gender.unique()

In [ ]:
#Gender Distribution 
df = data.Gender.value_counts().reset_index()

fig, ax = plt.subplots()
ax.pie(
    x=df["Gender"],
    startangle=90,
    labels=df['index'],
    autopct="%.0f%%",
#     shadow=True,
    explode=(0.03, 0, 0)
)
plt.title('Gender Distribution', fontsize=12);

In [ ]:
#Gender Value Counts in Different Column
for x in ['Education Level', 'Country', 'Job Category', 'Ethnicity']:
    data.groupby(x)['Gender'].value_counts().unstack().plot(kind='barh', figsize=(16, 6))
    plt.title(f'Gender Value Counts in Different {x}')

In [ ]:
data['Education Level'] = data['Education Level'].str.replace("Master's Degree", "Master's")

In [ ]:
# Gender distribution in each educational level
for x in data['Education Level'].unique():
    df = data.loc[data['Education Level']==x]['Gender'].value_counts().reset_index()
    
    fig, ax = plt.subplots()
    ax.pie(
        x=df["Gender"],
        startangle=90,
        labels=df['index'],
        autopct="%.0f%%",
#       shadow=True,
#         explode=(0.03, 0, 0)
            )
    plt.title(f"Gender Distribution of {x} Degree", fontsize=12)

In [ ]:
# Gender distribution in each Job Category
for x in data['Job Category'].unique():
    df = data.loc[data['Job Category']==x]['Gender'].value_counts().reset_index()
    
    fig, ax = plt.subplots()
    ax.pie(
        x=df["Gender"],
        startangle=90,
        labels=df['index'],
        autopct="%.0f%%",
#       shadow=True,
#         explode=(0.03, 0, 0)
            )
    plt.title(f"Gender Distribution in {x}", fontsize=12)

In [ ]:
# Gender distribution in each Job Category
for x in data['Job Category'].unique():
    df = data.loc[data['Job Category']==x]['Gender'].value_counts().reset_index()
    
    fig, ax = plt.subplots()
    ax.pie(
        x=df["Gender"],
        startangle=90,
        labels=df['index'],
        autopct="%.0f%%",
#       shadow=True,
#         explode=(0.03, 0, 0)
            )
    plt.title(f"Gender Distribution in {x}", fontsize=12)

In [ ]:
#Double for loop of each different column and its unique value
for x in ['Education Level', 'Country', 'Job Category', 'Ethnicity']:
    for y in data[x].unique():
        df = data.loc[data[x]==y]['Gender'].value_counts().reset_index()
        fig, ax = plt.subplots()
        ax.pie(
            x=df["Gender"],
            startangle=90,
            labels=df['index'],
            autopct="%.0f%%",
#       shadow=True,
#         explode=(0.03, 0, 0)
            )
        plt.title(f'Gender Distibution in Different {x} in {y}', fontsize=12)

In [ ]:
#Avg Salary and Avg Year of Experience for different gender
df = data.groupby('Gender')[['Salary', 'Years of Experience', 'Age']].mean()
df

In [ ]:
for x in ['Salary', 'Years of Experience', 'Age']:
    dfm = df.reset_index()
    sns.barplot(data=dfm.sort_values(x, ascending=False) , x='Gender', y=x)
    plt.title(f'Avg {x} for Different Gender', fontsize=12)
    plt.show()

In [ ]:
# Education Level Analysis

In [ ]:
data['Education Level'].value_counts()

In [ ]:
df = data['Education Level'].value_counts().reset_index()

fig, ax = plt.subplots()
ax.pie(
    x=df["Education Level"],
    startangle=90,
    labels=df['index'],
    autopct="%.0f%%",
    shadow=True,
    explode=(0.1, 0, 0, 0)
            )

plt.title('Education Level Distribution')

In [ ]:
#Avg Age, experience, salary for Different Education Level
for x in data.columns:
    if data[x].dtype != 'O':
        df = data.groupby('Education Level')[x].mean().sort_values(ascending=False).reset_index()
        plt.figure(figsize=(16, 4))
        sns.barplot(data=df, y='Education Level', x=x)
        plt.title(f"Avg {x} for Different Education Level")
        plt.show()

In [ ]:
#Avg salary of different education level of different job category
df = data.groupby(['Education Level', 'Job Category'])['Salary'].mean().unstack().T
df

In [ ]:
df.plot(kind='barh', figsize=(16, 15))
plt.title('Avg Salary for Different Job Category of Different Education Level');

In [ ]:
#Avg salary of different education level of different Country, ethnicity
for x in ['Country', 'Ethnicity']:
    df = data.groupby(['Education Level', x])['Salary'].mean().unstack().T
    df.plot(kind='barh', figsize=(10, 4))
    plt.title(f'Avg Salary of Different {x} of Different Education Level', fontsize=12)

In [ ]:
#Avg Salary of Different Country of different education level of differnet job category
for x in data['Country'].unique():
    df = data.loc[data['Country'] == x].groupby(['Education Level', 'Job Category'])['Salary'].mean().unstack().T
    df.plot(kind='barh', figsize=(16, 15))
    plt.title(f"Avg Salary of Different Job Category of Different Education Level in {x}")

In [ ]:
#Value_counts of each education level in different Country, Job Category, Ethnicity
for x in ['Country', 'Job Category', 'Ethnicity', 'Gender']:
    df = data.groupby(x)['Education Level'].value_counts().unstack()
    df.plot(kind='barh', figsize=(16, 8))
    plt.title(f'Education Level Value Counts in each {x}')

In [ ]:
#Job Category Value Counts in Different Education Level'
for x in data['Education Level'].unique():
    df = data.loc[data['Education Level'] == x]['Job Category'].value_counts().sort_values(ascending=False).reset_index()
#Pie chart
    fig, ax = plt.subplots()
    ax.pie(
        x=df["Job Category"],
        startangle=90,
        labels=df['index'],
        autopct="%.0f%%"
#         shadow=True,
#         explode=(0.1, 0, 0, 0)
            )
    plt.title(f'{x} Distribution in Different Job Category', fontsize=12)
    
#     plt.figure(figsize=(16, 8))
#     sns.barplot(data=df, x='index', y='Job Category')
#     plt.title(f'Job Category Value Counts in {x} Level')
#     plt.xticks(rotation=45)
#     plt.show()

In [ ]:
#Double for loop different educational level distribution in different Country, Gender, Ethnicity
for x in data['Education Level'].unique():
    for y in ['Country', 'Gender', 'Ethnicity']:
        df = data.loc[data['Education Level']==x][y].value_counts().reset_index()
        fig, ax = plt.subplots()
        ax.pie(
            x=df[y],
            startangle=90,
            labels=df['index'],
            autopct="%.0f%%",
            shadow=True,
#         explode=(0.1, 0, 0, 0)
            )
        plt.title(f'{x} Distribution in Different {y}', fontsize=12)

In [ ]:
#Job Title analysis

In [ ]:
len(data['Job Title'].unique())

In [ ]:
df = data.groupby('Job Title')[['Age', 'Years of Experience', 'Salary']].mean().sort_values('Salary', ascending=False)

df

In [ ]:
for x in df.columns:
    dfm = df.loc[:,[x]]
    plt.figure(figsize=(16, 5))
    sns.barplot(data=dfm.reset_index().sort_values(x, ascending=False)[:10], y='Job Title', x=x )
    plt.title(f'Top 10 Job Title with Highest {x}', fontsize=12)
    plt.show()

In [ ]:
#Years of experience analysis

In [ ]:
sns.histplot(data['Years of Experience'])

In [ ]:
data.head()

In [ ]:
#Top 10 Job Title with Highest max, mean, min of Years of Experience
df = data.groupby('Job Title')['Years of Experience'].agg(['mean', 'max'])

for x in df.columns:
    plt.figure(figsize=(10, 4))
    sns.barplot(data=df.reset_index().sort_values(x, ascending=False)[:10], y='Job Title', x=x)
    plt.title(f"Top 10 Job Title with Highest {x} of Years of Experience", fontsize=12)
    plt.show()

In [ ]:
df.reset_index()

In [ ]:
#Avg Years of Experience of differnet Job Category and Education Level
for x in ['Education Level', 'Job Category']:
    df = data.groupby(x)['Years of Experience'].mean().sort_values(ascending=False).reset_index()
    plt.figure(figsize=(16, 4))
    sns.barplot(data=df, y=x, x='Years of Experience')
    plt.axvline(data['Years of Experience'].mean(), ls='--', color='black', alpha=0.3)
    plt.title(f'Avg Years of Experience for each {x}')
    plt.show()

In [ ]:
#Avg Years of Experience of Different Gender of Different Education Level
df = data.groupby(['Education Level', 'Gender'])['Years of Experience'].mean().unstack()
df

In [ ]:
df.plot(kind='bar', rot=0)
plt.title('Avg Years of Experience of Different Gender of Different Education Level', fontsize=10);

In [ ]:
#Avg Years of Experience of Different Education Level of Different Job Category
df = data.groupby(['Education Level', 'Job Category'])['Years of Experience'].mean().unstack().T
df

In [ ]:
df.plot(kind='bar', figsize=(16, 8), rot=45)
plt.title('Avg Years of Experience of Different Education Level of Different Job Category');

In [ ]:
#Avg Years of Experience of Different Job Category of Different Country
df = data.groupby(['Country', 'Job Category'])['Years of Experience'].mean().unstack().T
df

In [ ]:
df.plot(kind='bar', figsize=(16, 8), rot=45)
plt.title('Avg Years of Experience of Different Job Category of Different Country');

In [ ]:
#Salalry Analysis

In [ ]:
sns.histplot(data['Salary'])

In [ ]:
#Top 10 Job Title with Highest max, mean, min of salary
df = data.groupby('Job Title')['Salary'].agg(['mean', 'max'])

for x in df.columns:
    plt.figure(figsize=(10, 4))
    sns.barplot(data=df.reset_index().sort_values(x, ascending=False)[:10], y='Job Title', x=x)
    plt.title(f"Top 10 Job Title with Highest {x} of Salary", fontsize=12)
    plt.show()

In [ ]:
for x in ['Country', 'Ethnicity', 'Gender']:
    df = data.groupby(x)['Salary'].mean().sort_values(ascending=False).reset_index()
    sns.barplot(data=df, x=x, y='Salary')
    plt.title(f"Avg Salary in Each {x}", fontsize=12)
    plt.show()

In [ ]:
#Avg Salary for Each Job Category
df = data.groupby('Job Category')['Salary'].mean().sort_values(ascending=False).reset_index()
plt.figure(figsize=(16, 8))
sns.barplot(data=df, x='Job Category', y='Salary')
plt.title("Avg Salary for Each Job Category", fontsize=12)
plt.xticks(rotation=30)
plt.show()

In [ ]:
#Avg Salary of Different Education Level in Different Job category in Differnet Country
#Plot can be find above on under Education Level analysis
def salary_country(country):
    if country in data.Country.unique():
        df = data.loc[data['Country'] == country].groupby(['Education Level', 'Job Category'])['Salary'].mean().unstack().T
        return df
    
    else:
        return 'The contry is not available'

data['Country'].unique()

In [ ]:
salary_country('China')

In [ ]:
salary_country('brazil')

In [ ]:
salary_country('USA')

In [ ]:
#Function return a dataframe of avg salary of each job category in each country

def country_job_salary(country):
    if country in data.Country.unique():
        df = data.loc[data['Country']==country].groupby('Job Category')['Salary'].mean()\
.sort_values(ascending=False).reset_index().set_index('Job Category').rename(columns={'Salary':country})
        return df
    else:
        print('The country is not available.')

In [ ]:
country_job_salary('China')

In [ ]:
for x in data.Country.unique():
    df = country_job_salary(x)
    plt.figure(figsize=(16, 6))
    sns.barplot(data=df.reset_index(), x='Job Category', y=x)
    plt.xticks(rotation=30)
    plt.title(f'Avg Salary of each Job Category in {x}');

In [ ]:
data.Country.unique()

In [ ]:
#Return average value of salary of each job category in each country

avg_salary_country = pd.DataFrame()

for x in data.Country.unique():
    df = country_job_salary(x)
    avg_salary_country = pd.concat([
        avg_salary_country, df
    ], axis=1)
    
avg_salary_country

In [ ]:
avg_salary_country.plot(kind='bar', figsize=(18, 8), rot=35)
plt.title('Avge Salary of each Job Category in each Country');

In [ ]:
#Avg Salary of Different Education Level in different Country

def education_salary(country):
    if country in data['Country'].unique():
        df = data.loc[data['Country'] == country].groupby('Education Level')['Salary'].mean()\
             .sort_values(ascending=False).reset_index()\
             .rename(columns={'Salary':country}).set_index('Education Level')
        return df 
    
    else:
        print('The country is not available from the dataset.')

In [ ]:
result_df = pd.DataFrame()

for x in data.Country.unique():
    df = education_salary(x)
    result_df = pd.concat([
        result_df, df
    ], axis=1)
    
result_df

In [ ]:
#Country Analysis

In [ ]:
data.Country.value_counts()

In [ ]:
df = data.Country.value_counts().reset_index()

fig, ax = plt.subplots()
ax.pie(
    x=df['Country'],
    startangle=90,
    labels=df['index'],
    autopct="%.0f%%",
    shadow=True,
    explode=(0.1,0.1,0,0,0)
    )

plt.title(f"Country Distribution", fontsize=12);

In [ ]:
# Each Educational Level Count in each Country 
for x in data.Country.unique():
    df = data.loc[data['Country'] == x]['Education Level'].value_counts().reset_index()
    sns.barplot(data=df, x='index', y='Education Level')
    plt.title(f'Educational Level Count in {x}', fontsize=12)
    plt.show()

In [ ]:
#Each Educational Level Count in each Country 
result_df = pd.DataFrame()
for x in data['Country'].unique():
    df = data[data['Country']==x]['Education Level'].value_counts().reset_index()\
         .rename(columns={'Education Level':x, 'index':'Education Level'}).set_index('Education Level')
    
    result_df = pd.concat([
        result_df, df
    ], axis=1)
    
result_df

In [ ]:
result_df.T.plot(kind='bar', rot=0, figsize=(16, 6))
plt.title('Educational Level Count in each Country');

In [ ]:
#Job category distribution in each country
df = data.groupby('Country')['Job Category'].value_counts().unstack().T.reset_index()
df.dropna(inplace=True)


for x in df.columns[1:]:
    fig, ax = plt.subplots()
    ax.pie(
        x=df[x],
        startangle=90,
        labels=df['Job Category'],
        autopct="%.0f%%",
#     shadow=True,
#         explode=[0.1, 0]
            )
    
    plt.title(f'Job Category Distribution in {x}', fontsize=12)

In [ ]:
# df = df.T
# df.columns = df.loc['Job Category']
# df.drop('Job Category', axis=0, inplace=True)
# df.reset_index(inplace=True)
df

In [ ]:
#Job Category Distribution in Different Country 
for x in df.columns[1:]:
    fig, ax = plt.subplots()
    ax.pie(
        x=df[x],
        startangle=90,
        labels=df['Country'],
        autopct="%.0f%%",
        shadow=True,
        explode=[0.1, 0, 0, 0, 0]
            )
    plt.title(f'{x} Distribution in Different Country', fontsize=10)

In [ ]:
# Correlation

In [ ]:
data.corr()['Salary']

In [ ]:
sns.pairplot(data)

In [ ]:
for x in ['Age', 'Years of Experience']:
    sns.lmplot(data=data, x='Salary', y=x)
    plt.title(f'Salary vs. {x}', fontsize=12)

In [ ]:
data.head()

In [ ]:
# Correlation of salary and job category
df = pd.concat([
    data.loc[:, ['Salary']],
    pd.get_dummies(data['Job Category'])
], axis=1)

df.corr()['Salary'].sort_values(ascending=False)

In [ ]:
# Correlation of salary and Education Level
df = pd.concat([
    data.loc[:, ['Salary']],
    pd.get_dummies(data['Education Level'])
], axis=1)

df.corr()['Salary'].sort_values(ascending=False)

In [ ]:
sns.heatmap(df.corr(), annot=True)

In [ ]:
data.head()