# Importing Libraries

# Loading Data

## Convert the Datatype of 'Date' column to Date-Time format.

## Add a new column ''year'' in the dataframe, which contains years only.

## Add a new column ''month'' as 2nd column in the dataframe, which contains month only.

## Show all the records where 'No. of Crimes' is 0. And, how many such records are there ?

## What is the maximum & minimum 'average_price' per year in england ?

## What is the Maximum & Minimum No. of Crimes recorded per area ?

## Show the total count of records of each area, where average price is less than 100000.