<div style="width:100%;text-align: center;"> <img align=middle src="https://images.unsplash.com/photo-1603094543704-64cdce2d2532?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8dG95b3RhJTIwY2Fyc3xlbnwwfDB8MHx8&auto=format&fit=crop&w=500&q=60" alt="Heat beating" style="height:366px;margin-top:3rem;"> </div>

# <h1 style='background:#B270A2; border:0; color:white'><center>üöòEDA: New Toyota Cars</center></h1>

# **<span style="color:#A66CFF;">üì∞About the Dataset</span>**

Toyota Motor Corporation is a Japanese multinational automotive manufacturer headquartered in Toyota City, Aichi, Japan. It was founded by Kiichiro Toyoda and incorporated on August 28, 1937. Toyota is one of the largest automobile manufacturers in the world, producing about 10 million vehicles per year.

# **<span style="color:#A66CFF;">üìÅAbout the file</span>**

Dataset contains 4847 rows and 4 columns

> 1 cars names: This column is for the prices of cars
> 2 ratings: This column is for over all ratings given to the vehicles by users
> 3 reviews: Total reviews given on car by users.
> 4 Price: This column is for the prices of brand new Toyota cars

In [ ]:
#Imports
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
#Custom Colors
class clr:
    S = '\033[1m' + '\033[96m'
    E = '\033[0m'
    
my_colors = ["#B270A2","#A66CFF","#9C9EFE", "#AFB4FF", "#B1E1FF"]

print(clr.S + "Notebook Color Scheme: " + clr.E)
sns.palplot(sns.color_palette(my_colors))

In [ ]:
#Environment check
import os
import warnings
warnings.filterwarnings("ignore")

## **<span style="color:#B270A2;">üìÉ Let's get the data</span>**

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
df = pd.read_csv('/kaggle/input/newtoyotacars/new-toyota-cars.csv')

In [ ]:
df.info()

**<span style="color:#E56B6F;">We can see that only 'ratings' has dtype - float64, rest all attributes are objects and we do not have any null values as well.</span>**

In [ ]:
df.describe()

In [ ]:
df.columns

In [ ]:
df.head()

**<span style="color:#E56B6F;">Here, ratings is only numerical data. Though we do consider price and number of reviews as numerics but this dataset treats them as objects. So, we need to make some adjustments. For that head to next step - Data Cleaning</span>**

## **<span style="color:#B270A2;">üßπData Cleaning</span>**

In [ ]:
df['price'].unique()

In [ ]:
df['price'] = df['price'].str.replace('$', '')
df['price'] = df['price'].str.replace(',', '')

In [ ]:
df['price'] = df['price'].str.replace('Not Priced', '0')

In [ ]:
#Drop all cars priced at $ 0
df = df[(df[['price']] != 0).all(axis=1)]

In [ ]:
df['price'].head()

In [ ]:
#Convert from Series object to int 
df['price'] = df['price'].astype(int)

In [ ]:
#df['reviews'].unique()

In [ ]:
df['reviews'] = df['reviews'].str.replace('(', '')
df['reviews'] = df['reviews'].str.replace(')', '')
df['reviews'] = df['reviews'].str.replace(',', '')
df['reviews'] = df['reviews'].str.replace('reviews', '')

In [ ]:
df['reviews'] = df['reviews'].str.replace(' ', '')

In [ ]:
df['reviews'] = df['reviews'].str.replace('review', '')

In [ ]:
#Convert from Series object to int 
df['reviews'] = df['reviews'].astype(int)

In [ ]:
df.head()

## **<span style="color:#B270A2;">ü•ΩLet's see what all we can explore in this dataset</span>**

> 1. What is the average price of a new car?

> 2. Which car is the most costliest and most affordable?

> 3. Which car has most and least reviews?

> 4. What would you say about a car having maximum an minimum rating?

> 5. Check the average ratings of Toyota Cars

>*Most Optimum Toyota Car*

In [ ]:
df.hist(bins = 50, figsize = (20,15), color = my_colors[4])

## **<span style="color:#9C9EFE;">1Ô∏è‚É£ What is the average price of a new car?</span>**

In [ ]:
average_price = df['price'].mean()
print("Average price of Toyota Cars is about $",average_price)

In [ ]:
plt.figure(figsize= (15,8))
plt.plot(df['price'], color = my_colors[2])
plt.show()

## **<span style="color:#9C9EFE;">2Ô∏è‚É£ Which car is the most costliest and most affordable?</span>**

In [ ]:
min_price = df['price'].min()
afford_car = df.loc[df['price'] == min_price, 'car names'].iloc[0]
print('The most affordable Toyota is', afford_car,'around - $', min_price)

In [ ]:
max_price = df['price'].max()
lux_car = df.loc[df['price'] == max_price, 'car names'].iloc[0]
print('The most priced Toyota is', lux_car,'around - $', max_price)

In [ ]:
plt.figure(figsize = (40,20))
sns.catplot(x = 'car names',
            y = 'price',
            kind = "bar",
            height = 7,
            aspect = 2,            
            data = df.head(30)).set(title = "Car vs Price");
plt.xticks(rotation=60)
plt.show()

## **<span style="color:#9C9EFE;">3Ô∏è‚É£ Which car has most and least reviews?</span>**

In [ ]:
min_review = df['reviews'].min()
min_review_car =df.loc[df['reviews'] == min_review, 'car names'].iloc[0]
print('The least reviewed Toyota is', min_review_car,' with ', min_review, ' reviews')

In [ ]:
max_review = df['reviews'].max()
max_review_car =df.loc[df['reviews'] == max_review, 'car names'].iloc[0]
print('The most reviewed Toyota is', max_review_car,' with ', max_review , ' reviews')

In [ ]:
plt.figure(figsize = (40,20))
sns.catplot(x = 'car names',
            y = 'reviews',
            kind = "bar",
            height = 7,
            aspect = 2,            
            data = df.head(30), color = '#E8A0BF').set(title = "Car vs Reviews");
plt.xticks(rotation=60)
plt.show()

## **<span style="color:#9C9EFE;">4Ô∏è‚É£ What would you say about a car having maximum an minimum rating?</span>**

In [ ]:
min_rate = df['ratings'].min()
low_rate_car = df.loc[df['ratings'] == min_rate, 'car names'].iloc[0]

print(low_rate_car, "has least rating of ", min_rate, " - Not Recommended to buy!")

In [ ]:
max_rate = df['ratings'].max()
high_rate_car = df.loc[df['ratings'] == max_rate, 'car names'].iloc[0]

print(high_rate_car, "has best rating of ", max_rate, " - Highly Recommended to buy!")

## **<span style="color:#9C9EFE;">5Ô∏è‚É£Let's check the average ratings of Toyota Cars</span>**

In [ ]:
avg_rate = df['ratings'].mean()
count = 0
for i in range(0, len(df['ratings'])):
    if (i >= avg_rate):
        count = count + 1
        
print('Average rating for Toyota cars is about ', round(avg_rate))

In [ ]:
# Check how many cars have rating above average rating

print("About", count, " out of ", len(df['ratings']),"Toyota Cars have 5 star ratings")

In [ ]:
plt.figure(figsize= (15,8))
sns.stripplot(x="car names", y="ratings", data=df.head(100), jitter=0.5).set(title = "Car vs Rating");
plt.xticks(rotation= 60)
plt.show()

**<span style="color:#E56B6F;"> Almost all cars have rating of 4 or above.</span>**

## **<span style="color:#cd486b;">üåü Most Optimum Toyota Car üåü</span>**

In [ ]:
# Let's find the most optimum car

optimum_car_rating = df.loc[df['price'] == min_price, 'ratings'].iloc[0]
opti_review = df.loc[df['car names'] == afford_car, 'reviews'].iloc[0]

print(afford_car, 'is the most affordable car costing about $', min_price, ", having ",optimum_car_rating, "star rating and ", opti_review," reviews." )

# **<span style="color:#A66CFF;">ü§òConclusion</span>**

**From the above analysis the optimum car to buy would be:**

**2021 Toyota Corolla LE is the most affordable car costing about $ 21330 , having  4.8 star rating and  2441  reviews.**

-------------------------------------------------------------------------------------------------------------------------

**<span style="color:#000000;">This marks the end of üöòEDA: New Toyota Cars</span>** 

**<span style="color:#000000;"> Stay Tuned for upcoming versions..</span>** 

**<span style="color:#000000;">Please share your feedback and suggestions and help me improve üòá </span>**