**INDIAN STARTUP FUNDING PROJECT**

Interested in the Indian startup ecosystem just like me? Wanted to know what type of startups are getting funded in the last few years? Wanted to know who are the important investors? Wanted to know the hot fields that get a lot of funding these days? This dataset is a chance to explore the Indian start up scene. Deep dive into funding data and derive insights into the future

**Dataset Information**: This dataset has funding information of the Indian startups from January 2015 to August 2017. It includes columns with the date funded, the city the startup is based out of, the names of the funders, and the amount invested (in USD).[](http://)

About the columns

SNo:-Serial Number

Date:-Date of Funding

StartupName:-Name of the startup

IndustryVertical:- Industry to which startup belongs

SubVertical:- Sub-Category of the industry type

CityLocation:- Location of the startup

InvestorsName:-Name of the investors

InvestmentType:- kind of funding

AmountInUSD:- Funding amount in USD

Remarks:- information related to the startups

** analysis some important questions which are related to startups India:-**

Q1). Number of unique Startups.

Q2). Top 10 Startups which are attrative means they have maximum number of Investors.

Q3). Top 10 Startups with maximum funding.

Q4). Top 10 Startups with minimum funding.

Q5). Number of Unique Investors.

Q6). Top 10 Investors in Indian ecosystem according to the total amount they invested in startups.

Q7). Top 10 industries which are favourite of Investors.

Q8). Top 10 Sub-industries in Technology industry according to number of times Investors invested in Startups.

Q9). Top 10 Industry where funding is maximum.

Q10). Top 10 cities which have maximum startups.

Q11). Top 10 cities which got maximum funding and their funding distribution.

Q12). Funding distribution in Indian Startups over Years.

Q13). Number of startups over months and over years.

Q14). Different type of funding (Investment type).

In [ ]:
# Importing useful Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [ ]:
df_startup=pd.read_csv("../input/indian-startup-funding/startup_funding.csv")

In [ ]:
#dataset shape
df_startup.shape

In [ ]:
# Basic information.
df_startup.info()

In [ ]:
#Looking the data
df_startup.head()

In [ ]:
df_startup.describe()

In [ ]:
df_startup.nunique()

In [ ]:
#find missing value
df_startup.isnull().sum()

In [ ]:
 #delete unwanted columns
 df_startup.drop('Remarks', axis=1, inplace=True)

In [ ]:
 # Replacing the commas in 'Amount in USD' feature
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x: str(x).replace(',', ''))

In [ ]:
# Fixing the faulty values in 'Amount in USD' feature
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("undisclosed", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("Undisclosed", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("unknown", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("14342000+", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("\\\\xc2\\\\xa010000000", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("\\\\xc2\\\\xa05000000", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("\\\\xc2\\\\xa019350000", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("\\\\xc2\\\\xa0600000", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("\\\\xc2\\\\xa020000000", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("\\\\xc2\\\\xa0N/A", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("\\\\xc2\\\\xa016200000", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("\\\\xc2\\\\xa0685000", "0"))
df_startup['Amount in USD'] = df_startup['Amount in USD'].apply(lambda x : str(x).replace("nan", "0"))

In [ ]:
# Converting to numeric data-type
df_startup['Amount in USD'] = pd.to_numeric(df_startup['Amount in USD'])

In [ ]:
# Checking dataset after cleaning it.
df_startup.head()


STARTUPS ANALYSIS

Q1). Number of unique Startups

In [ ]:
print(f"The numebr of Unique Startups are\t {df_startup['Startup Name'].nunique()} ")

Q2). Top 10 Startups which are attrative means they have maximum number of Investors.

In [ ]:
df_startup['Startup Name'].value_counts()[:10].plot(kind='bar', figsize=(12,4))
plt.show()

* Swiggy. Ubercap, Jugnoo they are in high demand by Investor.
* Maximum number of times startups got one time investment.

Q3). Top 10 Startups with maximum funding

In [ ]:
temp_df = df_startup.sort_values('Amount in USD', ascending=False, )
temp_df = temp_df[['Startup Name', 'Amount in USD']][:10].set_index('Startup Name', drop=True, )
temp_df.plot(kind='bar', figsize=(10,5))
plt.show()

temp_df.plot(kind='pie', subplots=True, figsize=(12,6), autopct='%.f%%')
plt.show()

temp_df.T

So Paytm and Flipkart were the startups that had the maximum investments

INVESTORS AND INDUSTRIES ANALYSIS

Q5). Number of Unique Investors

In [ ]:
print(f"The number of unique investors in Indian ecosystem between 2015 to 2017 are\t {df_startup['Investors Name'].nunique()}")

Q6). Top 10 Investors in Indian ecosystem according to the total amount they invested in startups

In [ ]:
investor = df_startup.groupby('Investors Name')['Amount in USD'].sum().reset_index()
investor.sort_values('Amount in USD', inplace=True, ascending=False)
investor.reset_index()[:10]

Q7). Top 10 industries which are favourite of Investors

In [ ]:
df_startup['Industry Vertical'].value_counts()[:10].reset_index()

* Consumer internet and Technology industries are in high demand by Investors.
* Their future is good. 
* If one want to start a new startup then they should start in these industries.
* It's good to see education industry in top 10

Q8). Top 10 Sub-industries in Technology industry according to number of times Investors invested in Startups.

In [ ]:
temp_df = df_startup[df_startup['Industry Vertical'].isin(['Technology','technology'])]
temp_df = temp_df['SubVertical'].value_counts()[:10].reset_index()
temp_df.columns = ['Sub Industry', 'Number of times']
temp_df.set_index('Sub Industry', drop=True, inplace=True)
temp_df.plot(kind='bar', figsize=(10,5))
plt.show()
temp_df.T

Q9). Top 10 Industry where funding is maximum.

In [ ]:
# converting ecommerce into Ecommerce
df_startup['Industry Vertical'] = df_startup['Industry Vertical'].apply(lambda x: 'ECommerce' if x=='eCommerce' else x)

new_df = df_startup.groupby('Industry Vertical')['Amount in USD'].sum().reset_index()
new_df.sort_values('Amount in USD', inplace=True, ascending=False)

new_df.set_index('Industry Vertical', inplace=True, drop=True)
new_df[:10].plot(kind='bar', figsize=(10,5))
plt.show()

new_df[:10].plot(kind='pie', subplots=True, figsize=(12,6), autopct='%.f%%')
plt.show()

new_df[:10].T

* ECommerce got maximum amount of funding followed by Consumer Internet and then by Technology.
* If one want to start a startup then they can start in these industries.

CITIES ANALYSIS

Q10). Top 10 cities which have maximum startups

In [ ]:
city = df_startup['City  Location'].value_counts()[:10].reset_index()
city.columns = ['City', 'Number of Startups']
city.set_index('City', drop=True, inplace=True)
city.plot(kind='bar', figsize=(10,5), title='Top 10 Cities which have maximum startups')
plt.show()

city.plot(kind='pie', subplots=True, figsize=(12,6), autopct='%.f%%')
plt.show()
city.T

* Bangalore,the silicon valley of India, is on top followed by Mumbai and then by Delhi.
* Jaipur is also in top 10 with 25 startups. A good start from Jaipur.
* Jaipur can be a hub of startups as there is huge space avilable in Jaipur and government is also come out with new schemes.

Q11). Top 10 cities which got maximum funding and their funding distribution

In [ ]:
# Dealing with duplicates name.
l = ['Bangalore', 'Bangalore/ Bangkok', 'SFO / Bangalore','Seattle / Bangalore', 'Bangalore / SFO',
     'Bangalore / Palo Alto', 'Bangalore / San Mateo', 'Bangalore / USA',   ]
df_startup['City  Location'] = df_startup['City  Location'].apply(lambda x: 'Bangalore' if x in l else x )

city_df = df_startup.groupby('City  Location')['Amount in USD'].sum().reset_index()
city_df.sort_values('Amount in USD', ascending=False, inplace=True)
city_df = city_df[:10]
city_df.reset_index(inplace=True, drop=True)
city_df.set_index('City  Location', inplace=True, drop=True)
city_df.plot(kind='bar', figsize=(12,6), title='Top 10 cities which got maximum funding')
plt.show()

city_df.plot(kind='pie', figsize=(12,6), autopct='%.f%%', subplots=True)
plt.show()

city_df.T

50% of funding was done in Bangalore city.
Mumbai have so many startups but have less funding.

check out their distribution

In [ ]:
# top_city is the cities which have maximum funding.
top_city = city_df.index
temp_df = df_startup[df_startup['City  Location'].isin(top_city)]
temp_df = temp_df[['City  Location', 'Amount in USD']]

plt.figure(figsize=(12,6))
sns.swarmplot(data=temp_df, x=temp_df['City  Location'], y=temp_df['Amount in USD'])

plt.show()

* we can see there are so many outliers in Bangalore and in New Delhi.

FUND ANALYSIS

Q12). Different type of funding (Investment type).

In [ ]:
# Dealing with incorrect entries.
def convert(x):
    if x== 'SeedFunding':
        return 'Seed Funding'
    elif x== 'PrivateEquity':
        return 'Private Equity'
    elif x== 'Crowd funding':
        return 'Crowd Funding'
    else:
        return x

df_startup['InvestmentnType'] = df_startup['InvestmentnType'].apply(convert)

df_startup['InvestmentnType'].value_counts().plot(kind='bar', figsize=(12,6), title='Type of Investment')
plt.show()

df_startup['InvestmentnType'].value_counts().plot(kind='pie', figsize=(12,6), subplots=True, autopct='%.f%%')
plt.show()